# Generated by Django 3.0.1 on 2020-07-22 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_registeruser'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeruser',
            name='profile_picture',
            field=models.ImageField(blank=True, default='avatar.png', upload_to=''),
        ),
    ]
