# Generated by Django 3.0.1 on 2020-07-22 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_registeruser_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.RegisterUser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='is_approve',
            field=models.BooleanField(default=True),
        ),
    ]
